Update twilio-video-ios to 3.7.0 for iOS 14
blackuy/react-native-twilio-video-webrtc pull request #377
Opened 2020-09-06 19:24 UTC by stevelizcano

This PR updates the pod for iOS 14 support. Full details on the change are here:

https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-3x

Basically it removes the need for a new NetworkPrivacyPolicy request and removes local networking for peer-to-peer rooms.

Tests locally on a localhost with two phones, works without a problem.

Solved #376

2020-09-07 00:14 UTC, ceaglest requested changes
Please do not pin to minor version 3.7, use major versions instead. Twilio Video uses semantic versioning.

Previously this project was stuck on 3.2.3 which is from April and is missing important updates made since then. This process will repeat itself if you pin to a minor version. We do not back port fixes to every minor version.

2020-09-07 11:33 UTC, stevelizcano commented
@slycoder Up to you, I adjusted to 3.7 but can do straight 3 if you want

2020-09-08 01:32 UTC, ceaglest approved these changes

2020-09-08 01:37 UTC, slycoder commented
I'm fine either way.  I'm sympathetic to the idea that pinning to major versions is the best practice.  OTOH, I know others who tend to pin minor versions and upgrade only sparingly.

Thanks for the discussions @ceaglest and thanks @stevelizcano for putting this together!  I'll go ahead and merge this and if/when we ever get burned again, I'll just peg to a major version.

2020-09-08 01:37 UTC, slycoder approved these changes

2020-09-08 01:38 UTC, slycoder approved these changes

2020-09-08 01:38 UTC, merged

2020-09-08 01:39 UTC, slycoder commented
Also @ceaglest if you or anyone else from twilio is interested in contributing in an official capacity, lemme know!

2020-09-08 01:44 UTC, ceaglest commented
Thank you @stevelizcano for putting together the PR and @slycoder for the review. This project is very popular and we wanted to make sure that react users get the best experience on iOS 14. Your quick response is greatly appreciated.

> Also @ceaglest if you or anyone else from twilio is interested in contributing in an official capacity, lemme know!

Absolutely, we will keep this in mind. For now you have my gratitude for maintaining this project and providing an alternative means to use Twilio Video.